#! /bin/bash
# 

for i in *.sam; do
    #file=$(echo $i | cut -f7 -d/)
	ids=$(echo $i | cut -f1 -d.)   # keep the path in id  (for output)
    #id=$(echo $id | cut -f7 -d/)
    #RG=\'@RG'\t'ID:${id}\'
    echo $ids
    ~/hts_tools/samtools-1.3.1/samtools view -S -u $i -o ${ids}.bam

done


